name: Unity Tests

on: [ "push" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: dotnet tool install --global NuGetForUnity.Cli
    - uses: actions/checkout@v3
    - run: nugetforunity restore
    - uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: .